### ISSUE TITLE
Meth cooker not appearing

### ISSUE THREAD

**Issue by Crectrum** [teigCoding/qb-drugproduce#2]
Hey, I tried out the script but whenever I go inside the meth location the meth cooker itself does not show, why is this?
![Skjermbilde 2023-10-01 181514](https://github.com/teigCoding/qb-drugproduce/assets/146657566/a6a88c75-dcba-4d39-a4be-2eece5e4e0a1)

**Comment by farmmechanic71** [comment]
Have the same issue, Discord support nobody answered.

**Comment by teigCoding** [comment]
This is not a standard QB MLO. This MLO has to be purchased. You can change coords to another MLO if wanted.
